services:
  adlinkfly-telegram-bot:
    container_name: adlinkfly-telegram-bot
    build: .
    ports:
      - "${HOST_PORT:-8080}:8080"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - BOT_TOKEN=${BOT_TOKEN}
      - ADLINKFLY_TOKEN=${ADLINKFLY_TOKEN}
      - START=${START}
      - HELP=${HELP}